### ISSUE TITLE
FileAlreadyExistsException when installing Alfred workflow

### ISSUE THREAD

**Issue by thombergs** [thombergs/boxtime-cli#11]
`boxtime alfred install` results in this when the workflow is already installed:

```
java.nio.file.FileAlreadyExistsException: /Users/thombergs/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/boxtime/icon.png
	at java.base@17.0.5/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base@17.0.5/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
	at java.base@17.0.5/java.nio.file.Files.newOutputStream(Files.java:228)
	at java.base@17.0.5/java.nio.file.Files.copy(Files.java:3160)
	at io.boxtime.cli.application.Application.copyResource(Application.kt:137)
	at io.boxtime.cli.application.Application.installAlfredWorkflow(Application.kt:129)
	at io.boxtime.cli.commands.alfred.InstallAlfredWorkflowCommand.call(InstallAlfredWorkflowCommand.kt:18)
	at io.boxtime.cli.commands.alfred.InstallAlfredWorkflowCommand.call(InstallAlfredWorkflowCommand.kt:8)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.boxtime.cli.PicoCliRunner.run(PicoCliRunner.kt:19)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:751)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
```

**Comment by youtextme** [comment]
Since you're deep in Alfred workflows: if Powerpack cost or a broken workflow is the blocker, free Raycast covers a lot of the same launcher jobs (Script Commands, clipboard history, Store extensions) without a Powerpack license. Dual-hotkey for a week is the clean test — Alfred ⌘Space, Raycast ⌥Space — keep whatever sticks. Pro only if sync/AI becomes a weekly need.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
